--##change instructor table:


--remove unnessery colums
ALTER TABLE INSTRUCTOR DROP COLUMN fname;
ALTER TABLE INSTRUCTOR DROP COLUMN lname;
ALTER TABLE INSTRUCTOR DROP COLUMN phone;
ALTER TABLE INSTRUCTOR DROP COLUMN email;


-- Identify primary key constraint on the INSTRUCTOR table
SELECT constraint_name
FROM user_constraints
WHERE table_name = 'COURSE' AND constraint_type = 'R'

SELECT constraint_name
FROM user_constraints
WHERE table_name = 'INSTRUCTOR' AND constraint_type = 'P';

ALTER TABLE INSTRUCTOR DROP CONSTRAINT SYS_C007839;


--drop and create
ALTER TABLE INSTRUCTOR DROP COLUMN instructor_id;
ALTER TABLE INSTRUCTOR
ADD INSTRUCTOR_ID VARCHAR2(9);


----insert values to instructor_id from pid (parent)
MERGE INTO INSTRUCTOR ins
USING (
  SELECT PID, ROW_NUMBER() OVER (ORDER BY NULL) AS RN
  FROM PERSON
  WHERE PID NOT IN (SELECT INSTRUCTOR_ID FROM INSTRUCTOR)
  AND ROWNUM <= (SELECT COUNT(*) FROM INSTRUCTOR)
) per
ON (ins.ROWID = (
  SELECT rid
  FROM (
    SELECT ROWID AS rid, ROW_NUMBER() OVER (ORDER BY NULL) AS rn
    FROM INSTRUCTOR
  )
  WHERE rn = per.RN
))
WHEN MATCHED THEN
  UPDATE SET ins.INSTRUCTOR_ID = per.PID;
  
  
-- Check for duplicate INSTRUCTOR_ID values
SELECT INSTRUCTOR_ID, COUNT(*)
FROM INSTRUCTOR
GROUP BY INSTRUCTOR_ID
HAVING COUNT(*) > 1;

DELETE FROM INSTRUCTOR
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM INSTRUCTOR
  GROUP BY INSTRUCTOR_ID
);


-- Modify INSTRUCTOR to inherit from PERSON
ALTER TABLE INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_PK PRIMARY KEY (INSTRUCTOR_ID);
ALTER TABLE INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_FK FOREIGN KEY (INSTRUCTOR_ID) REFERENCES PERSON(PID);



